# Yaml code for creating a deployment and service of frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # this is the specification of pods
      containers:
        - name: frontendcontainer
          image: muqeem/kubernetestask-frontend:latest
          ports:
           - containerPort: 80
---
# Yaml for making the external service for frontend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: frontend-service

spec:
  type: NodePort
  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
